// <auto-generated />
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SettingsContext))]
    [Migration("20230322191916_ClearDatabaseMigration")]
    partial class ClearDatabaseMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Domain.SettingsEntities.ApplicationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Test")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSettings");
                });

            modelBuilder.Entity("Domain.SettingsEntities.SensorSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MaxAlarmEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxTemp")
                        .HasColumnType("REAL");

                    b.Property<bool>("MinAlarmEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinTemp")
                        .HasColumnType("REAL");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SensorSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
